<?php

namespace JTDSoft\Essentials;

class Languages
{
    protected static $languages = [
        'ab' => ['Abkhaz', 'аҧсуа бызшәа, аҧсшәа', 'abk'],
        'aa' => ['Afar', 'Afaraf', 'aar'],
        'af' => ['Afrikaans', 'Afrikaans', 'afr'],
        'ak' => ['Akan', 'Akan', 'aka'],
        'sq' => ['Albanian', 'Shqip', 'sqi'],
        'am' => ['Amharic', 'አማርኛ', 'amh'],
        'ar' => ['Arabic', 'العربية', 'ara'],
        'an' => ['Aragonese', 'aragonés', 'arg'],
        'hy' => ['Armenian', 'Հայերեն', 'hye'],
        'as' => ['Assamese', 'অসমীয়া', 'asm'],
        'av' => ['Avaric', 'авар мацӀ, магӀарул мацӀ', 'ava'],
        'ae' => ['Avestan', 'avesta', 'ave'],
        'ay' => ['Aymara', 'aymar aru', 'aym'],
        'az' => ['Azerbaijani', 'azərbaycan dili', 'aze'],
        'bm' => ['Bambara', 'bamanankan', 'bam'],
        'ba' => ['Bashkir', 'башҡорт теле', 'bak'],
        'eu' => ['Basque', 'euskara, euskera', 'eus'],
        'be' => ['Belarusian', 'беларуская мова', 'bel'],
        'bn' => ['Bengali, Bangla', 'বাংলা', 'ben'],
        'bh' => ['Bihari', 'भोजपुरी', 'bih'],
        'bi' => ['Bislama', 'Bislama', 'bis'],
        'bs' => ['Bosnian', 'bosanski jezik', 'bos'],
        'br' => ['Breton', 'brezhoneg', 'bre'],
        'bg' => ['Bulgarian', 'български език', 'bul'],
        'my' => ['Burmese', 'ဗမာစာ', 'mya'],
        'ca' => ['Catalan', 'català', 'cat'],
        'ch' => ['Chamorro', 'Chamoru', 'cha'],
        'ce' => ['Chechen', 'нохчийн мотт', 'che'],
        'ny' => ['Chichewa, Chewa, Nyanja', 'chiCheŵa, chinyanja', 'nya'],
        'zh' => ['Chinese', '中文 (Zhōngwén), 汉语, 漢語', 'zho'],
        'cv' => ['Chuvash', 'чӑваш чӗлхи', 'chv'],
        'kw' => ['Cornish', 'Kernewek', 'cor'],
        'co' => ['Corsican', 'corsu, lingua corsa', 'cos'],
        'cr' => ['Cree', 'ᓀᐦᐃᔭᐍᐏᐣ', 'cre'],
        'hr' => ['Croatian', 'hrvatski jezik', 'hrv'],
        'cs' => ['Czech', 'čeština, český jazyk', 'ces'],
        'da' => ['Danish', 'dansk', 'dan'],
        'dv' => ['Divehi, Dhivehi, Maldivian', 'ދިވެހި', 'div'],
        'nl' => ['Dutch', 'Nederlands, Vlaams', 'nld'],
        'dz' => ['Dzongkha', 'རྫོང་ཁ', 'dzo'],
        'en' => ['English', 'English', 'eng'],
        'eo' => ['Esperanto', 'Esperanto', 'epo'],
        'et' => ['Estonian', 'eesti, eesti keel', 'est'],
        'ee' => ['Ewe', 'Eʋegbe', 'ewe'],
        'fo' => ['Faroese', 'føroyskt', 'fao'],
        'fj' => ['Fijian', 'vosa Vakaviti', 'fij'],
        'fi' => ['Finnish', 'suomi, suomen kieli', 'fin'],
        'fr' => ['French', 'français, langue française', 'fra'],
        'ff' => ['Fula, Fulah, Pulaar, Pular', 'Fulfulde, Pulaar, Pular', 'ful'],
        'gl' => ['Galician', 'galego', 'glg'],
        'ka' => ['Georgian', 'ქართული', 'kat'],
        'de' => ['German', 'Deutsch', 'deu'],
        'el' => ['Greek (modern)', 'ελληνικά', 'ell'],
        'gn' => ['Guaraní', 'Avañe\'ẽ', 'grn'],
        'gu' => ['Gujarati', 'ગુજરાતી', 'guj'],
        'ht' => ['Haitian, Haitian Creole', 'Kreyòl ayisyen', 'hat'],
        'ha' => ['Hausa', '(Hausa) هَوُسَ', 'hau'],
        'he' => ['Hebrew (modern)', 'עברית', 'heb'],
        'hz' => ['Herero', 'Otjiherero', 'her'],
        'hi' => ['Hindi', 'हिन्दी, हिंदी', 'hin'],
        'ho' => ['Hiri Motu', 'Hiri Motu', 'hmo'],
        'hu' => ['Hungarian', 'magyar', 'hun'],
        'ia' => ['Interlingua', 'Interlingua', 'ina'],
        'id' => ['Indonesian', 'Bahasa Indonesia', 'ind'],
        'ie' => ['Interlingue', 'Originally called Occidental; then Interlingue after WWII', 'ile'],
        'ga' => ['Irish', 'Gaeilge', 'gle'],
        'ig' => ['Igbo', 'Asụsụ Igbo', 'ibo'],
        'ik' => ['Inupiaq', 'Iñupiaq, Iñupiatun', 'ipk'],
        'io' => ['Ido', 'Ido', 'ido'],
        'is' => ['Icelandic', 'Íslenska', 'isl'],
        'it' => ['Italian', 'italiano', 'ita'],
        'iu' => ['Inuktitut', 'ᐃᓄᒃᑎᑐᑦ', 'iku'],
        'ja' => ['Japanese', '日本語 (にほんご)', 'jpn'],
        'jv' => ['Javanese', 'ꦧꦱꦗꦮ', 'jav'],
        'kl' => ['Kalaallisut, Greenlandic', 'kalaallisut, kalaallit oqaasii', 'kal'],
        'kn' => ['Kannada', 'ಕನ್ನಡ', 'kan'],
        'kr' => ['Kanuri', 'Kanuri', 'kau'],
        'ks' => ['Kashmiri', 'कश्मीरी, كشميري‎', 'kas'],
        'kk' => ['Kazakh', 'қазақ тілі', 'kaz'],
        'km' => ['Khmer', 'ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ', 'khm'],
        'ki' => ['Kikuyu, Gikuyu', 'Gĩkũyũ', 'kik'],
        'rw' => ['Kinyarwanda', 'Ikinyarwanda', 'kin'],
        'ky' => ['Kyrgyz', 'Кыргызча, Кыргыз тили', 'kir'],
        'kv' => ['Komi', 'коми кыв', 'kom'],
        'kg' => ['Kongo', 'Kikongo', 'kon'],
        'ko' => ['Korean', '한국어, 조선어', 'kor'],
        'ku' => ['Kurdish', 'Kurdî, كوردی‎', 'kur'],
        'kj' => ['Kwanyama, Kuanyama', 'Kuanyama', 'kua'],
        'la' => ['Latin', 'latine, lingua latina', 'lat'],
        'lb' => ['Luxembourgish, Letzeburgesch', 'Lëtzebuergesch', 'ltz'],
        'lg' => ['Ganda', 'Luganda', 'lug'],
        'li' => ['Limburgish, Limburgan, Limburger', 'Limburgs', 'lim'],
        'ln' => ['Lingala', 'Lingála', 'lin'],
        'lo' => ['Lao', 'ພາສາລາວ', 'lao'],
        'lt' => ['Lithuanian', 'lietuvių kalba', 'lit'],
        'lu' => ['Luba-Katanga', 'Tshiluba', 'lub'],
        'lv' => ['Latvian', 'latviešu valoda', 'lav'],
        'gv' => ['Manx', 'Gaelg, Gailck', 'glv'],
        'mk' => ['Macedonian', 'македонски јазик', 'mkd'],
        'mg' => ['Malagasy', 'fiteny malagasy', 'mlg'],
        'ms' => ['Malay', 'bahasa Melayu, بهاس ملايو‎', 'msa'],
        'ml' => ['Malayalam', 'മലയാളം', 'mal'],
        'mt' => ['Maltese', 'Malti', 'mlt'],
        'mi' => ['Māori', 'te reo Māori', 'mri'],
        'mr' => ['Marathi (Marāṭhī)', 'मराठी', 'mar'],
        'mh' => ['Marshallese', 'Kajin M̧ajeļ', 'mah'],
        'mn' => ['Mongolian', 'Монгол хэл', 'mon'],
        'na' => ['Nauruan', 'Dorerin Naoero', 'nau'],
        'nv' => ['Navajo, Navaho', 'Diné bizaad', 'nav'],
        'nd' => ['Northern Ndebele', 'isiNdebele', 'nde'],
        'ne' => ['Nepali', 'नेपाली', 'nep'],
        'ng' => ['Ndonga', 'Owambo', 'ndo'],
        'nb' => ['Norwegian Bokmål', 'Norsk bokmål', 'nob'],
        'nn' => ['Norwegian Nynorsk', 'Norsk nynorsk', 'nno'],
        'no' => ['Norwegian', 'Norsk', 'nor'],
        'oc' => ['Occitan (post 1500)', 'Occitan', 'oci'],
        'oj' => ['Ojibwa', 'ᐊᓂᔑᓈᐯᒧᐎᓐ / Anishinaabemowin', 'oji'],
        'or' => ['Oriya', 'ଓଡ଼ିଆ', 'ori'],
        'om' => ['Oromo', 'Oromoo', 'orm'],
        'os' => ['Ossetian, Ossetic', 'Иронау', 'oss'],
        'pi' => ['Pali', 'Pāli / पाऴि', 'pli'],
        'pa' => ['Panjabi, Punjabi', 'ਪੰਜਾਬੀ / पंजाबी / پنجابي', 'pan'],
        'ps' => ['Pashto, Pushto', 'پښتو', 'pus'],
        'fa' => ['Farsi', 'فارسی', 'far'],
        'pl' => ['Polish', 'Polski', 'pol'],
        'pt' => ['Portuguese', 'Português', 'por'],
        'qu' => ['Quechua', 'Runa Simi', 'que'],
        'rm' => ['Raeto Romance', 'Rumantsch', 'roh'],
        'rn' => ['Rundi', 'Kirundi', 'run'],
        'ru' => ['Russian', 'Русский', 'rus'],
        'sm' => ['Samoan', 'Gagana Samoa', 'smo'],
        'sg' => ['Sango', 'Sängö', 'sag'],
        'sa' => ['Sanskrit', 'संस्कृतम्', 'san'],
        'sc' => ['Sardinian', 'Sardu', 'srd'],
        'sr' => ['Serbian', 'Српски', 'srp'],
        'sn' => ['Shona', 'chiShona', 'sna'],
        'sd' => ['Sindhi', 'सिनधि', 'snd'],
        'si' => ['Sinhala, Sinhalese', 'සිංහල', 'sin'],
        'sk' => ['Slovak', 'Slovenčina', 'slk'],
        'sl' => ['Slovenian', 'Slovenščina', 'slv'],
        'so' => ['Somali', 'Soomaaliga', 'som'],
        'st' => ['Sotho, Southern', 'Sesotho', 'sot'],
        'nr' => ['South Ndebele', 'isiNdebele', 'nbl'],
        'es' => ['Spanish', 'Español', 'spa'],
        'su' => ['Sundanese', '	Basa Sunda', 'sun'],
        'sw' => ['Swahili', 'Kiswahili', 'swa'],
        'ss' => ['Swati', 'SiSwati', 'ssw'],
        'sv' => ['Swedish', 'Svenska', 'swe'],
        'tl' => ['Tagalog', 'Tagalog', 'tgl'],
        'ty' => ['Tahitian', 'Reo Mā`ohi', 'tah'],
        'tg' => ['Tajik', 'Тоҷикӣ', 'tgk'],
        'ta' => ['Tamil', 'தமிழ்', 'tam'],
        'tt' => ['Tatar', 'Tatarça', 'tat'],
        'te' => ['Telugu', 'తెలుగు', 'tel'],
        'th' => ['Thai', 'ไทย / Phasa Thai', 'tha'],
        'bo' => ['Tibetan', 'བོད་ཡིག / Bod skad', 'bod'],
        'ti' => ['Tigrinya', 'ትግርኛ', 'tir'],
        'to' => ['Tonga (Tonga Islands)', 'Lea Faka-Tonga', 'ton'],
        'ts' => ['Tsonga', 'Xitsonga', 'tso'],
        'tn' => ['Tswana', 'Setswana', 'tsn'],
        'tr' => ['Turkish', 'Türkçe', 'tur'],
        'tk' => ['Turkmen', 'Туркмен / تركمن', 'tuk'],
        'tw' => ['Twi', 'Twi', 'twi'],
        'ug' => ['Uighur, Uyghur', 'Uyƣurqə / ئۇيغۇرچە', 'uig'],
        'uk' => ['Ukrainian', 'Українська', 'ukr'],
        'ur' => ['Urdu', 'اردو', 'urd'],
        'uz' => ['Uzbek', 'Ўзбек', 'uzb'],
        've' => ['Venda', 'Tshivenḓa', 'ven'],
        'vi' => ['Vietnamese', 'Việtnam', 'vie'],
        'vo' => ['Volapük', 'Volapük', 'vol'],
        'wa' => ['Walloon', 'Walon', 'wln'],
        'cy' => ['Welsh', 'Cymraeg', 'cym'],
        'fy' => ['Western Frisian', 'Frysk', 'fry'],
        'wo' => ['Wolof', 'Wollof', 'wol'],
        'xh' => ['Xhosa', 'isiXhosa', 'xho'],
        'yi' => ['Yiddish','ייִדיש', 'yid'],
        'yo' => ['Yoruba', 'Yorùbá', 'yor'],
        'za' => ['Zhuang, Chuang', 'Cuengh / Tôô / 壮语', 'zha'],
        'zu' => ['Zulu', 'isiZulu', 'zul']
    ];

    public static function existsByIso($iso)
    {
        return isset(static::$languages[strtolower($iso)]);
    }

    public static function getByIso($iso)
    {
        return static::$languages[strtolower($iso)] ?? null;
    }

    public static function getNameByIso($iso)
    {
        return static::getByIso($iso)[0] ?? null;
    }

    public static function getNativeNameByIso($iso)
    {
        return static::getByIso($iso)[1] ?? null;
    }

    public static function getIso2ByIso($iso)
    {
        return static::getByIso($iso)[2] ?? null;
    }

    public static function all()
    {
        return self::$languages;
    }
}
